cart/urls.py
from django.urls import path

from . import views

app_name='cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('cart/add/<int:ingredient_id>/', views.cart_add, name='cart_add'),
    path('cart/remove/<int:ingredient_id>/', views.cart_remove, name='cart_remove'),
    path('cart/cocktail_all_ingredients_add/<int:cocktail_id>/', views.cocktail_all_ingredients_add,
         name='cocktail_all_ingredients_add'),
]

config/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

import orders
from shop import views
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    # shop and cocktail_base
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('all_ingredients/', views.all_ingredients, name='all_ingredients'),
    path('cocktail/<int:cocktail_id>/', views.cocktail_detail, name='cocktail_detail'),
    path('ingredient/<int:ingredient_id>/', views.ingredient_detail, name='ingredient_detail'),

    # cart
    path('cart/', include('cart.urls', namespace='cart')),

    # orders
    path('orders/', include('orders.urls', namespace='orders')),

    # authorization
    path('singup/', views.singupuser, name='singupuser'),
    path('logout/', views.logoutuser, name='logoutuser'),
    path('login/', views.loginuser, name='loginuser'),

    #search
    path('search/', include('search.urls', namespace='search')),

    ]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name='orders'

urlpatterns = [
    path('orders/create', views.order_create, name='order_create'),
    path('all_orders/', views.all_orders, name='all_orders'),
    path('order_detail/<int:order_id>', views.order_detail, name='order_detail'),
]

cart/forms.py
from django import forms

INGREDIENT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddIngredientForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=INGREDIENT_QUANTITY_CHOICES, coerce=int, widget=forms.Select(attrs = {'class':"form-select"}))
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Ingredient, Cocktail
from .cart import Cart
from .forms import CartAddIngredientForm

@login_required(login_url='http://127.0.0.1:8000/login/')
@require_POST
def cart_add(request, ingredient_id):
    cart = Cart(request)
    ingredient = get_object_or_404(Ingredient, id=ingredient_id)
    form = CartAddIngredientForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(ingredient=ingredient,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


@login_required(login_url='http://127.0.0.1:8000/login/')
def cocktail_all_ingredients_add(request, cocktail_id):
    cart = Cart(request)
    cocktail = get_object_or_404(Cocktail, id=cocktail_id)
    for ingredient in cocktail:
        cart.add(ingredient)
    return redirect('cart:cart_detail')


def cart_remove(request, ingredient_id):
    cart = Cart(request)
    ingredient = get_object_or_404(Ingredient, id=ingredient_id)
    cart.remove(ingredient)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    Your shopping cart
{% endblock %}
{% block content %}
<h1 xmlns:cart="http://www.w3.org/1999/xhtml">Your shopping cart</h1>
    <table class="cart" style="width:100%">
        <thead>
        <tr>
            <th style="width:15%"><h6>Image</h6></th>
            <th style="width:30%"><h6>Product</h6></th>
            <th style="width:15%"><h6>Quantity</h6></th>
            <th style="width:20%"><h6>Price</h6></th>
            <th style="width:20%"><h6>Unit price</h6></th>
            <th style="width:20%"><h6>Remove</h6></th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with ingredient=item.ingredient %}
                <tr style="padding-bottom:24px">
                    <td style="padding-bottom: 24px;">
                        <a href="{{ ingredient.get_absolute_url }}">
                            <img style="max-width:100px; border-radius:24px" src="
                                {% if ingredient.image %}
                                    {{ ingredient.image.url }}
                                {% else %}
                                    {% static "cart/no_image.jpg" %}
                                {% endif %}">
                        </a>
                    </td>
                    <td><h7>{{ ingredient.title }}</h7></td>
                    <td><div style="padding-left:16px;"><h7>{{ item.quantity }}</h7></div></td>
                    <td class="num"><h7>${{ item.price }}</h7></td>
                    <td class="num"><h7>${{ item.total_price }}</h7></td>
                    <td><a style="margin-left: 12px" role="button" class="btn btn-primary styled-button"
                           href="{% url "cart:cart_remove" ingredient.id %}">Remove
                        </a>
                    </td>

                </tr>


            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td><h6>Total</h6></td>
            <td colspan="4"></td>
            <td class="num"><h5>${{ cart.get_total_price }}</h5></td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a style="margin-left: 12px" role="button" class="btn btn-primary styled-button" href="{% url "all_ingredients" %}" class="button light">Continue shopping</a>
        <a style="margin-left: 12px" role="button" class="btn btn-primary styled-button" href="{% url "orders:order_create" %}" class="button">Checkout</a>
    </p>
{% endblock %}